version: 2

builds:
  - skip: true

release:
  extra_files:
    - glob: dyld-tools-universal.tar.gz

checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: dyld-tools-universal.tar.gz

homebrew_casks:
  - name: dyld-tools
    repository:
      owner: blacktop
      name: homebrew-tap
      branch: master
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/blacktop/darwin-dyld-build"
    description: "Apple dyld tools built for macOS"
    url_template: "https://github.com/blacktop/darwin-dyld-build/releases/download/{{ .Tag }}/dyld-tools-universal.tar.gz"
    artifacts:
      - "dyld_info"
      - "dyld_shared_cache_util"
